"""
Curated reference list of known GenAI tools, organized by category.
This is the candidate pool the updater draws from when filling empty slots.

Each entry is (name, url). URLs should be canonical homepages.
"""

REFERENCE_TOOLS = {
    "Agentic AI": [
        ("Devin", "https://devin.ai"),
        ("CrewAI", "https://www.crewai.com"),
        ("AutoGPT", "https://agpt.co"),
        ("Copilot Studio", "https://www.microsoft.com/en-us/microsoft-copilot/microsoft-copilot-studio"),
        ("Manus", "https://manus.im"),
        ("Sana", "https://sana.ai"),
        ("StackAI", "https://www.stack-ai.com"),
        ("Beam", "https://beam.ai"),
        ("n8n", "https://n8n.io"),
        ("LangGraph", "https://www.langchain.com/langgraph"),
        ("Adept", "https://www.adept.ai"),
        ("MultiOn", "https://www.multion.ai"),
        ("Cognosys", "https://www.cognosys.ai"),
        ("AgentGPT", "https://agentgpt.reworkd.ai"),
        ("Lindy", "https://www.lindy.ai"),
        ("Relevance AI", "https://relevanceai.com"),
        ("Cognition Labs", "https://www.cognition.ai"),
        ("Replit Agent", "https://replit.com"),
    ],
    "Chatbot": [
        ("ChatGPT", "https://chatgpt.com"),
        ("Claude", "https://claude.ai"),
        ("Gemini", "https://gemini.google.com"),
        ("Grok", "https://grok.com"),
        ("DeepSeek", "https://www.deepseek.com"),
        ("Copilot", "https://copilot.microsoft.com"),
        ("Mistral Le Chat", "https://chat.mistral.ai"),
        ("Pi", "https://pi.ai"),
        ("Poe", "https://poe.com"),
        ("HuggingChat", "https://huggingface.co/chat"),
        ("Qwen Chat", "https://chat.qwen.ai"),
        ("Kimi", "https://kimi.moonshot.cn"),
        ("Character.ai", "https://character.ai"),
        ("You.com", "https://you.com"),
    ],
    "Conducting research": [
        ("Perplexity", "https://www.perplexity.ai"),
        ("Elicit", "https://elicit.com"),
        ("Consensus", "https://consensus.app"),
        ("NotebookLM", "https://notebooklm.google.com"),
        ("scite", "https://scite.ai"),
        ("SciSpace", "https://typeset.io"),
        ("Research Rabbit", "https://www.researchrabbit.ai"),
        ("Semantic Scholar", "https://www.semanticscholar.org"),
        ("Connected Papers", "https://www.connectedpapers.com"),
        ("Iris.ai", "https://iris.ai"),
        ("Scholarcy", "https://www.scholarcy.com"),
        ("Genei", "https://www.genei.io"),
        ("Litmaps", "https://www.litmaps.com"),
        ("ChatPDF", "https://www.chatpdf.com"),
        ("Humata", "https://www.humata.ai"),
    ],
    "Creating and editing images": [
        ("Midjourney", "https://www.midjourney.com"),
        ("DALL-E 3", "https://openai.com/dall-e-3"),
        ("Adobe Firefly", "https://www.adobe.com/products/firefly.html"),
        ("Ideogram", "https://ideogram.ai"),
        ("Stable Diffusion", "https://stability.ai"),
        ("Leonardo.Ai", "https://leonardo.ai"),
        ("Imagen", "https://deepmind.google/technologies/imagen"),
        ("Nano Banana", "https://nanobanana.ai"),
        ("Flux", "https://blackforestlabs.ai"),
        ("Recraft", "https://www.recraft.ai"),
        ("Krea", "https://www.krea.ai"),
        ("Playground", "https://playground.com"),
        ("Canva Magic Studio", "https://www.canva.com/magic-studio"),
        ("NightCafe", "https://creator.nightcafe.studio"),
        ("Civitai", "https://civitai.com"),
    ],
    "Creating and editing presentations": [
        ("Gamma", "https://gamma.app"),
        ("Beautiful.ai", "https://www.beautiful.ai"),
        ("MagicSlides", "https://www.magicslides.app"),
        ("SlidesAI", "https://www.slidesai.io"),
        ("Slidebean", "https://slidebean.com"),
        ("Pitch", "https://pitch.com"),
        ("Tome", "https://tome.app"),
        ("Decktopus", "https://www.decktopus.com"),
        ("Plus AI", "https://www.plusdocs.com"),
        ("Presentations.ai", "https://presentations.ai"),
        ("Sendsteps", "https://www.sendsteps.com"),
        ("Prezi AI", "https://prezi.com"),
    ],
    "Creating and editing sound": [
        ("ElevenLabs", "https://elevenlabs.io"),
        ("Suno", "https://suno.com"),
        ("Udio", "https://www.udio.com"),
        ("Descript", "https://www.descript.com"),
        ("Speechify", "https://speechify.com"),
        ("Murf.AI", "https://murf.ai"),
        ("PlayHT", "https://playhtai.com"),
        ("Resemble AI", "https://www.resemble.ai"),
        ("WellSaid Labs", "https://wellsaidlabs.com"),
        ("Boomy", "https://boomy.com"),
        ("AIVA", "https://www.aiva.ai"),
        ("Soundraw", "https://soundraw.io"),
        ("LALAL.AI", "https://www.lalal.ai"),
        ("Krisp", "https://krisp.ai"),
    ],
    "Creating and editing text": [
        ("Claude", "https://claude.ai"),
        ("Grammarly", "https://www.grammarly.com"),
        ("Notion AI", "https://www.notion.so/product/ai"),
        ("Writer", "https://writer.com"),
        ("Jasper", "https://www.jasper.ai"),
        ("Copy.ai", "https://www.copy.ai"),
        ("Writesonic", "https://writesonic.com"),
        ("QuillBot", "https://quillbot.com"),
        ("Wordtune", "https://www.wordtune.com"),
        ("Rytr", "https://rytr.me"),
        ("Sudowrite", "https://www.sudowrite.com"),
        ("LanguageTool", "https://languagetool.org"),
        ("ProWritingAid", "https://prowritingaid.com"),
        ("Anyword", "https://anyword.com"),
    ],
    "Creating and editing video": [
        ("Runway", "https://runwayml.com"),
        ("Sora", "https://openai.com/sora"),
        ("Pika", "https://pika.art"),
        ("HeyGen", "https://www.heygen.com"),
        ("Kling AI", "https://klingai.com"),
        ("Synthesia", "https://www.synthesia.io"),
        ("CapCut", "https://www.capcut.com"),
        ("Opus Clip", "https://www.opus.pro"),
        ("invideo", "https://invideo.io"),
        ("D-ID", "https://www.d-id.com"),
        ("Veed", "https://www.veed.io"),
        ("Pictory", "https://pictory.ai"),
        ("Fliki", "https://fliki.ai"),
        ("Hailuo", "https://hailuoai.video"),
        ("Luma Dream Machine", "https://lumalabs.ai/dream-machine"),
        ("Veo", "https://deepmind.google/technologies/veo"),
    ],
    "Email management": [
        ("Superhuman", "https://superhuman.com"),
        ("Shortwave", "https://www.shortwave.com"),
        ("Fyxer", "https://www.fyxer.com"),
        ("SaneBox", "https://www.sanebox.com"),
        ("MailMaestro", "https://www.maestrolabs.com"),
        ("Mailbutler", "https://www.mailbutler.io"),
        ("Spike", "https://www.spikenow.com"),
        ("Missive", "https://missiveapp.com"),
        ("EmailTree", "https://emailtree.ai"),
        ("Lavender", "https://www.lavender.ai"),
        ("Smartwriter", "https://www.smartwriter.ai"),
    ],
    "Learning and education": [
        ("Khanmigo", "https://www.khanmigo.ai"),
        ("Duolingo Max", "https://www.duolingo.com"),
        ("NotebookLM", "https://notebooklm.google.com"),
        ("Docebo", "https://www.docebo.com"),
        ("360Learning", "https://360learning.com"),
        ("Absorb", "https://www.absorblms.com"),
        ("TalentLMS", "https://www.talentlms.com"),
        ("NovoEd", "https://www.novoed.com"),
        ("Coursera Coach", "https://www.coursera.org"),
        ("Quizlet", "https://quizlet.com"),
        ("Socratic", "https://socratic.org"),
        ("Brainly", "https://brainly.com"),
        ("ELSA Speak", "https://elsaspeak.com"),
    ],
    "Scheduling management": [
        ("Reclaim.ai", "https://reclaim.ai"),
        ("Motion", "https://www.usemotion.com"),
        ("Vimcal", "https://www.vimcal.com"),
        ("Amie", "https://amie.so"),
        ("Cal.ai", "https://cal.ai"),
        ("Akiflow", "https://akiflow.com"),
        ("Kronologic", "https://www.kronologic.com"),
        ("Calendly", "https://calendly.com"),
        ("x.ai", "https://x.ai"),
        ("Trevor", "https://trevorai.com"),
        ("Sunsama", "https://www.sunsama.com"),
        ("Magical", "https://www.getmagical.com"),
    ],
    "Task automation": [
        ("Zapier", "https://zapier.com"),
        ("Make", "https://www.make.com"),
        ("n8n", "https://n8n.io"),
        ("Bardeen", "https://www.bardeen.ai"),
        ("Workato", "https://www.workato.com"),
        ("Jitterbit", "https://www.jitterbit.com"),
        ("Tray.ai", "https://tray.ai"),
        ("Pipedream", "https://pipedream.com"),
        ("IFTTT", "https://ifttt.com"),
        ("Automate.io", "https://automate.io"),
        ("Levity", "https://levity.ai"),
        ("Mindstudio", "https://www.mindstudio.ai"),
    ],
    "Transcription": [
        ("Otter.ai", "https://otter.ai"),
        ("Fireflies", "https://fireflies.ai"),
        ("tl;dv", "https://tldv.io"),
        ("Fathom", "https://fathom.video"),
        ("Trint", "https://trint.com"),
        ("Rev", "https://www.rev.com"),
        ("Verbit", "https://verbit.ai"),
        ("Sonix", "https://sonix.ai"),
        ("Happy Scribe", "https://www.happyscribe.com"),
        ("Whisper", "https://openai.com/research/whisper"),
        ("Grain", "https://grain.com"),
        ("Krisp", "https://krisp.ai"),
        ("Read.ai", "https://www.read.ai"),
    ],
    "Translation and localization": [
        ("DeepL", "https://www.deepl.com"),
        ("Lokalise", "https://lokalise.com"),
        ("Phrase", "https://phrase.com"),
        ("Weglot", "https://www.weglot.com"),
        ("Smartling", "https://www.smartling.com"),
        ("Transifex", "https://www.transifex.com"),
        ("Lilt", "https://lilt.com"),
        ("Crowdin", "https://crowdin.com"),
        ("Memsource", "https://www.memsource.com"),
        ("Unbabel", "https://unbabel.com"),
        ("Google Translate", "https://translate.google.com"),
        ("Reverso", "https://www.reverso.net"),
    ],
    "Writing and analyzing code": [
        ("GitHub Copilot", "https://github.com/features/copilot"),
        ("Cursor", "https://cursor.com"),
        ("Windsurf", "https://windsurf.com"),
        ("Amazon Q", "https://aws.amazon.com/q"),
        ("Claude Code", "https://www.anthropic.com/claude-code"),
        ("Replit", "https://replit.com"),
        ("Sourcegraph", "https://sourcegraph.com"),
        ("Tabnine", "https://www.tabnine.com"),
        ("Codeium", "https://codeium.com"),
        ("Aider", "https://aider.chat"),
        ("Cline", "https://cline.bot"),
        ("Bolt", "https://bolt.new"),
        ("v0", "https://v0.dev"),
        ("Lovable", "https://lovable.dev"),
        ("Continue", "https://www.continue.dev"),
        ("Cody", "https://sourcegraph.com/cody"),
    ],
}


def all_tools():
    """Yield (category, name, url) for every tool in the reference list."""
    for category, tools in REFERENCE_TOOLS.items():
        for name, url in tools:
            yield category, name, url


def tools_for_category(category):
    """Return list of (name, url) tuples for a given category."""
    return REFERENCE_TOOLS.get(category, [])
